apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      volumes:
      - name: app-volume
        emptyDir: {}
      - name: app-secret
        secret:
          secretName: flask-app-secret
      initContainers:
      - name: install-deps
        image: python:3.8-slim
        command: ['sh', '-c', 'pip install -r /app/requirements.txt']
        volumeMounts:
        - name: app-volume
          mountPath: /app-install
        - name: app-secret
          mountPath: /app
      containers:
      - name: flask-app
        image: python:3.8-slim
        command: ["python", "/app/app.py"]
        volumeMounts:
        - name: app-volume
          mountPath: /app
        - name: app-secret
          mountPath: /app-config
        ports:
        - containerPort: 5000
