apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
spec:
  volumes:
    - name: app-volume
      emptyDir: {}
  initContainers:
    - name: install-deps
      image: python:3.8-slim
      command:
        - sh
        - -c
        - |
          pip install -r /app/requirements.txt
      volumeMounts:
        - name: app-volume
          mountPath: /app
  containers:
    - name: flask-app
      image: python:3.8-slim
      command:
        - python
        - /app/app.py
      volumeMounts:
        - name: app-volume
          mountPath: /app
